---
title: "Registration Status Report"
subtitle: " "
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_width: 7
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
params:
  course: 1
  term: 1
  opt: 1
  tables: 1
  rmd_file: 1
  output_dir_base: 1
  output_filename: 1
---

```{r setup, include=FALSE,  fig.width = 10, fig.height = 12}
library(kableExtra)
library(rmarkdown)
library(dplyr)
library(tidyr)
library(DT)


flagged <- params$tables[["flagged"]]

drops <- flagged[["drops"]]
dips <- flagged[["dips"]]
bumps <- flagged[["bumps"]]
high_fall_sophs <- flagged[["high_fall_sophs"]]
prev_courses <- flagged[["prev_courses"]]
waits <- flagged[["waits"]]
squeezes <- flagged[["squeezes"]]
thresholds <- flagged[["thresholds"]]

knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE, dpi=200, fig.height=11,out.height="100%")
```


### Filtering Options
```{r  results="asis", echo=FALSE} 
for (i in 1:length(thresholds)) {
  cat(paste0(names(thresholds[i]),": ",thresholds[i],"<br>"))
}
```


### Column Explanations

<style>
td {
border: 1px solid black;
padding: 1rem;
}
</style>

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}


tabl <- "
| Column Name   | Explanation                                                     |
| -----------:  | :-------------------------------------------------------------- | 
| enrolled      | student enrollment via latest retrieved DESR                    | 
| avg_size      | average section size                                            | 
| dr_early      | early drops (before census)                   |
| dr_late       | late drops (after census)                     | 
| dr_all        | all drops                                     |
| cl_total      | total registrants for course, including those who have dropped |
| squeeze       | ratio of available seats to mean drops (closer to zero -> less wiggle room) |
| impacted      | rough number of students outside SD |
"
cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```

(de_mean, dl_mean, da_mean: mean early, late, and total drops for this course per semester type)


### Courses with longer WAITING LIST than usual
```{r echo=FALSE} 
    datatable(waits,class = 'cell-border stripe')
```

### Courses with a bit of a SQUEEZE
```{r echo=FALSE} 
  squeezes <- squeezes %>% select(TERM,SUBJ_CRSE,enrolled,sections,avg_size,avail,waiting,gen_ed_area,de_mean,dl_mean,da_mean,squeeze)
  
  colnames(squeezes) <- c("TERM","SUBJ_CRSE","ENRL","SECTS","SECT_SIZE","AVAIL","WAIT","GE_AREA","DE_MEAN","DL_MEAN","DA_MEAN","SQUEEZE")
    
  datatable(squeezes,class = 'cell-border stripe')
```

### More DROPS than usual
```{r echo=FALSE} 
    datatable(drops,class = 'cell-border stripe')
```

### Bigger enrollment DIP than usual
```{r echo=FALSE} 
    datatable(dips,class = 'cell-border stripe')
```


### Bigger enrollment BUMP than usual
```{r echo=FALSE} 
    datatable(bumps,class = 'cell-border stripe')
```


