academic_studies_drop_cols <- c(
  "Current Time Status Code", 
  "Residency", 
  "First Minor Code", 
  "Second Minor Code", 
  "Student Population", 
  "Expected Grad Date", 
  "Catalog Academic Period",
  "Preferred Gender",
  "IPEDS Race", 
  "Deceased Status",
  "IPEDS Race",
  "African American Race Ind",
  "American Indian Race Ind",
  "Asian Race Ind",
  "Hispanic Race Ind",
  "Native Hawaiian Race Ind",
  "US Nonresident Race Ind",
  "White Race Ind",
  "Semester Credits Attempted",
  "Semester Credits Earned",
  "Semester GPA",
  "Semester GPA Credits",
  "Institution Credits Attempted",
  "Institution Credits Earned",
  "Institution GPA",
  "Institution GPA Credits",
  "Institution Quality Points",
  "Overall Credits Attempted",
  "Overall Credits Earned",
  "Deans List",
  "STARRS ID", 
  "Citizenship Type", 
  "Permit Registration Ind",
  "Academic Standing End Code",
  "Academic Standing End",
  "Academic Standing Code",
  "Academic Standing",
  "Primary Advisor (LFMI)",
  "Primary Advisor Person ID",
  "Pell Eligible Indicator",
  "First Generation Indicator")

class_lists_drop_cols <- c(
  "Meeting Days",
  "Meeting Time",
  "Maximum Enrollment",
  "Course Group",
  "CIP Code",
  "Course Max Credits",
  "Schedule Type",
  "Schedule Attribute Code",
  "Schedule Attribute",
  "Current Age",
  "IPEDS Race",
  "Student Level Code",
  "Student Population Code",
  "Student Population",
  "Residency Indicator",
  "Residency Code",
  "Residency",
  "Dual Credit",
  "Freshman Cohort")
