---
title: "Registration Status Report"
subtitle: " "
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_width: 7
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
params:
  course: 1
  term: 1
  opt: 1
  tables: 1
  rmd_file: 1
  output_dir_base: 1
  output_filename: 1
---

```{r setup, include=FALSE,  fig.width = 10, fig.height = 12}
library(kableExtra)
library(rmarkdown)
library(dplyr)
library(tidyr)

flagged <- params$tables[["flagged"]]

drops <- flagged[["drops"]]
dips <- flagged[["dips"]]
bumps <- flagged[["bumps"]]
high_fall_sophs <- flagged[["high_fall_sophs"]]
prev_courses <- flagged[["prev_courses"]]
waits <- flagged[["waits"]]
squeezes <- flagged[["squeezes"]]
thresholds <- flagged[["thresholds"]]

knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE, dpi=200, fig.height=11,out.height="100%")
```


### Filtering Options
```{r  results="asis", echo=FALSE} 
for (i in 1:length(thresholds)) {
  cat(paste0(names(thresholds[i]),": ",thresholds[i],"<br>"))
}
```



```{r flagged, results="asis", echo=FALSE} 

    cat(paste0("#### ","Courses with longer WAITING LIST than usual\n"))
    
    table <- kbl(waits,digits=2)  %>%   
      kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11) %>% 
      scroll_box(width = "100%", height = "300px")

    print(table)

    
        cat(paste0("#### ","Courses with many sophomores in the fall\n"))
    
    table <- kbl(high_fall_sophs,digits=2)  %>%   
      kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11) %>% 
      scroll_box(width = "100%", height = "300px")

    print(table)


    cat(paste0("#### ","Courses with a bit of a SQUEEZEl\n"))
    
    table <- kbl(squeezes,digits=2)  %>%   
      kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11) %>% 
      scroll_box(width = "100%", height = "300px")

    print(table)


    
    cat(paste0("#### ","More DROPS than usual\n"))
    
    table <- kbl(drops,digits=2)  %>%   
      kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 12) %>% 
      scroll_box(width = "100%", height = "300px")

    print(table)


   cat(paste0("#### ","Bigger enrollment DIP than usual\n"))
    
    table <- kbl(dips,digits=2)  %>%   
      kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 12) %>% 
      scroll_box(width = "100%", height = "300px")

    print(table)
    
    
  cat(paste0("#### ","Bigger enrollment BUMP than usual\n"))

    table <- kbl(bumps,digits=2)  %>%   
      kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 12) %>% 
      scroll_box(width = "100%", height = "300px")

    print(table)
  
```

