---
title: "Trends Report"
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_width: 7
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
params:
  dept: 1
  term: 1
  tables: 1
---

```{r setup, include=FALSE,  fig.width = 10, fig.height = 12}
library(kableExtra)
library(rmarkdown)
library(dplyr)
library(tidyr)

# make easier to access param data
dept <- params$dept

summary_by_term <- params$tables[["summary_by_term"]]
summary_across_terms <- params$tables[["summary_across_terms"]]
agg_by_major <- params$tables[["agg_by_major"]]
agg_by_class <- params$tables[["agg_by_class"]]
grades_summary <- params$tables[["grades_summary"]]
                     
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE, dpi=200, fig.height=11,out.height="100%")
```

---
title: "`r dept` Summer Report "
subtitle: " "
---

### All courses
```{r results="asis", echo=FALSE} 

terms <- unique(summary_by_term$TERM)

for (term in terms) {
  cat(paste0("#### ",term ,"\n"))

  table <- kbl(summary_by_term %>%  filter (TERM == term) %>% select(-c(1:2)),digits=2)  %>%   kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11,  position = "left") %>% 
    scroll_box(width = "100%", height = "300px")
  
  print(table)
}
```

<hr>    



### Enrollment Aggregates across Terms
```{r results="asis", echo=FALSE} 
    
summary_across_terms <- summary_across_terms %>% select(-c(1))


    table <- kbl(summary_across_terms,digits=2)  %>%   kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11,  position = "left") %>%  scroll_box(width = "100%", height = "300px")

    print(table)
    
```

<hr>    

### Rollcall by Major
```{r results="asis", echo=FALSE} 

courses <- unique(agg_by_major$SUBJ_CRSE)

for (course in courses) {

  #cat(paste0("#### ",term_text[which(num.labs == term)] ,"\n"))
    cat(paste0("#### ",course ,"\n"))


    table <- kbl(agg_by_major %>% filter(SUBJ_CRSE == course),digits=2)  %>%   kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11,  position = "left") %>% scroll_box(width = "100%", height = "300px")

    print(table)
}    
```

<hr>
    
    
### Rollcall by Student Classification
```{r results="asis", echo=FALSE} 
   
for (course in courses) {

      cat(paste0("#### ",course ,"\n"))

    table <- kbl(agg_by_class %>% filter(SUBJ_CRSE == course),digits=2)  %>%   kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11,  position = "left") #%>% scroll_box(width = "100%", height = "300px")

    print(table)

}    
```

<hr>


### Grade Distribution
```{r results="asis", echo=FALSE} 
    
    table <- kbl(grades_summary,digits=2)  %>%   kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),latex_options = c("striped","hold_position","condensed"), full_width=F, font_size = 11,  position = "center")

    print(table)
    
```
