---
title: "Forecast Report"
subtitle: " "
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_width: 7
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
params:
  course: 1
  term: 1
  opt: 1
  tables: 1
  rmd_file: 1
  output_dir_base: 1
  output_filename: 1
---

```{r setup, include=FALSE,  fig.width = 10, fig.height = 12}
  library(kableExtra)
  library(rmarkdown)
  library(dplyr)
  library(tidyr)

  forecasts <- params$tables[["forecasts"]]


  knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE, dpi=200, fig.height=11,out.height="100%")
```


#### Filtering Options
```{r  results="asis", echo=FALSE} 
cat("term: ", opt$term)

cat("<br> part of term: ", opt$pt)

cat("<br> inst method: ", opt$im)

cat("<br> level: ", opt$level,"\n")

    
    cols <- c("TERM","SUBJ_CRSE","enrolled","cl_total", "sections", "avg_size", "avail","conduit","major","c_accr","avg_c_accr","m_accr","avg_m_accr","m_cl_accr","avg_m_cl_accr","sections","diff_fr_prev")
    forecast_filtered <- forecasts %>% select(cols)
    
    forecast_filtered_fall <- forecast_filtered %>% filter (substring(TERM,5,6) == 80)
    forecast_filtered_spring <- forecast_filtered %>% filter (substring(TERM,5,6) == 10)
    forecast_filtered_summer <- forecast_filtered %>% filter (substring(TERM,5,6) == 60)
    
    cat("\n")
    
    cat(paste0("#### ","FALL forecasts\n"))

    for (course in unique(forecast_filtered_fall$SUBJ_CRSE)) {
      cat(paste0("##### ",course,"\n"))
      table <- kbl(forecast_filtered_fall %>% filter (SUBJ_CRSE == course),digits=2)  %>% 
        kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                      latex_options = c("striped","hold_position","condensed"), position="center", full_width=F)
      
      print(table)
    }
    
    cat("\n")
    cat(paste0("#### ","SPRING forecasts\n"))

    for (course in unique(forecast_filtered_spring$SUBJ_CRSE)) {
      cat(paste0("##### ",course,"\n"))
      table <- kbl(forecast_filtered_spring %>% filter (SUBJ_CRSE == course),digits=2)  %>% 
        kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), position="center", full_width=F)
      print(table)
    }
    
    cat("\n")
    
    cat(paste0("#### ","SUMMER forecasts\n"))

    for (course in unique(forecast_filtered_summer$SUBJ_CRSE)) {
      cat(paste0("##### ",course,"\n"))
      table <- kbl(forecast_filtered_summer %>% filter (SUBJ_CRSE == course),digits=2)  %>% 
        kable_styling(bootstrap_options = c("striped", "hover", "condensd", "responsive"),
                    latex_options = c("striped","hold_position","condensed"), font_size=11, position="center", full_width=F)
      print(table)
    }
    
```

